export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };

export interface ConsentRecord {
  id: string;
  userId: string;
  purpose: string;
  version: string;
  granted: boolean;
  source?: string | null;
  metadata?: string | null;
  createdAt: Date;
}

export interface PrivacyExport {
  exportedAt: string;
  user: Record<string, unknown>;
  accounts: Record<string, unknown>[];
  sessions: Record<string, unknown>[];
  consents: Array<{
    id: string;
    purpose: string;
    version: string;
    granted: boolean;
    source?: string | null;
    metadata?: JsonValue | null;
    createdAt: string;
  }>;
  application?: Record<string, unknown>;
}

export interface PrivacyKitOptions {
  /**
   * Enable the user-facing data export endpoint. Default: true.
   */
  export?: {
    enabled?: boolean;
    includeAccounts?: boolean;
    includeSessions?: boolean;
    /**
     * Add application-specific data to the export. Keep secrets out of this object.
     */
    extend?: (input: { userId: string }) =>
      | Promise<Record<string, unknown>>
      | Record<string, unknown>;
  };

  /**
   * Consent-history storage and endpoints. Default: enabled.
   */
  consent?: {
    enabled?: boolean;
    /**
     * Optional allow-list. Empty/omitted means any non-empty purpose up to 64 chars.
     */
    purposes?: readonly string[];
    maxMetadataBytes?: number;
  };

  /**
   * Anonymize the Better Auth identity and revoke access. Default: enabled.
   */
  anonymize?: {
    enabled?: boolean;
    placeholderName?: string;
    keepConsentHistory?: boolean;
    /**
     * Add app-specific user fields that must be blanked/replaced during anonymization.
     */
    additionalUserFields?: (input: {
      userId: string;
      user: Record<string, unknown>;
    }) => Promise<Record<string, unknown>> | Record<string, unknown>;
    before?: (input: { userId: string }) => Promise<void> | void;
    after?: (input: { userId: string }) => Promise<void> | void;
  };

  /**
   * Permanent deletion endpoint. Disabled by default because Better Auth's built-in
   * delete-user flow can provide stronger verification for many applications.
   */
  hardDelete?: {
    enabled?: boolean;
    before?: (input: { userId: string }) => Promise<void> | void;
    after?: (input: { userId: string }) => Promise<void> | void;
  };

  schema?: {
    /** Physical database table/model name generated by Better Auth CLI. */
    consentModelName?: string;
  };
}
